import { describe, it, expect, vi, beforeAll, beforeEach, afterAll } from "vitest";
import path from "path";
import fs from "fs/promises";
import { DesqueezeProcessor } from "../../src/main/processors/desqueeze-processor.js";
import { RawConverterService } from "../../src/main/services/raw-converter.js";

// Suppress logger noise during tests
vi.mock("../../src/main/logger.js", () => ({
	default: { info: vi.fn(), error: vi.fn(), debug: vi.fn(), warn: vi.fn() },
}));

// Mocking external dependencies that use binaries
vi.mock("../../src/main/services/binary-resolver.js");
vi.mock("../../src/main/processors/dng-operations.js", () => {
	const fs = require("fs/promises"); // Use require inside mock factory
	const DngOperations = vi.fn();
	DngOperations.prototype.setBinaryResolver = vi.fn();
	DngOperations.prototype.writeDesqueezeTag = vi.fn();

	// Mock these to write a dummy file so we can verify the path logic
	DngOperations.prototype.convertRAWToDNG = vi.fn().mockImplementation(async (inPath, outPath) => {
		await fs.writeFile(outPath, "Mock DNG generated by test");
	});
	DngOperations.prototype.convertBitmapToDNG = vi.fn().mockImplementation(async (outPath, args) => {
		await fs.writeFile(outPath, "Mock DNG generated by test");
	});

	DngOperations.prototype.finalizeDNG = vi.fn();
	DngOperations.prototype.inspectLayout = vi.fn().mockResolvedValue({
		rawGroup: "IFD0",
		previewGroup: null,
		currentScale: 1,
	});
	return { DngOperations };
});
vi.mock("../../src/main/services/exiftool-service.js", () => ({
	ExifToolService: {
		getInstance: vi.fn(() => ({
			shutdown: vi.fn(),
			read: vi.fn().mockResolvedValue({}),
			write: vi.fn().mockResolvedValue({}),
			// The mock DNG has no preview to pull, so the raw path skips it
			extractPreview: vi.fn().mockResolvedValue(false),
		})),
	},
}));

// Create a custom mock for the RawConverterService
const fixtureTiffPath = path.resolve("tests/fixtures/bitmap-c.tif");
const mockRawConverter = {
	setBinaryResolver: vi.fn(),
	convertToTiff: vi.fn().mockImplementation(async () => {
		// Create a unique temp file for each run so RawProcessor can delete it safely
		const tempPath = path.resolve(`tests/fixtures/temp-${Date.now()}-${Math.random()}.tif`);
		await fs.copyFile(fixtureTiffPath, tempPath);
		return tempPath;
	}),
};

const outDir = path.resolve("tests/fixtures/desqueezed");

describe("Pipeline Integration", () => {
	const processor = new DesqueezeProcessor({ rawConverter: mockRawConverter });

	const inputFiles = [
		{ name: "bitmap-a.jpg", type: "bitmap" },
		{ name: "bitmap-b.png", type: "bitmap" },
		{ name: "bitmap-c.tif", type: "bitmap" },
		{ name: "raw.ARW", type: "raw" },
	];

	const outputFormats = [
		{ format: "jpg", options: { quality: 80 } },
		{ format: "png", options: { compressionLevel: 2 } },
		{ format: "tiff", options: { compression: "lzw" } },
		{ format: "webp", options: { quality: 80 } },
		// DNG is mocked, but we should still test the pipeline routing
		{ format: "dng", options: {} },
	];

	// Cartesian product of inputs × formats
	const testCases = inputFiles.flatMap(file =>
		outputFormats.map(fmt => ({ ...file, ...fmt }))
	);

	// Clean output directory before the suite
	beforeAll(async () => {
		await fs.rm(outDir, { recursive: true, force: true });
		await fs.mkdir(outDir, { recursive: true });
	});

	// Reset mock call counts between tests so assertions are per-test
	beforeEach(() => {
		mockRawConverter.convertToTiff.mockClear();
	});

	// Clean up stray temp files that may have leaked from mock convertToTiff
	afterAll(async () => {
		const fixtureDir = path.resolve("tests/fixtures");
		const files = await fs.readdir(fixtureDir);
		for (const f of files) {
			if (f.startsWith("temp-") && f.endsWith(".tif")) {
				await fs.unlink(path.join(fixtureDir, f)).catch(() => {});
			}
		}
	});

	it.each(testCases)("should process $name to $format", async ({ name, type, format, options }) => {
		const inputPath = path.resolve(`tests/fixtures/${name}`);
		const ratioX = 1.33;
		const ratioY = 1.0;
		const outputRaw = { format, options };

		const outputPath = await processor.process(inputPath, ratioX, ratioY, outputRaw);

		const expectedExt = format === "tiff" ? ".tif" : `.${format}`;
		expect(outputPath.toLowerCase()).toContain(expectedExt);

		// Verify file was created (Mock DNGs are now written to disk too)
		const stats = await fs.stat(outputPath);
		expect(stats.size).toBeGreaterThan(0);

		// Verify the mock was called exactly once for this test case
		if (type === "raw" && format !== "dng") {
			expect(mockRawConverter.convertToTiff).toHaveBeenCalledOnce();
		} else {
			expect(mockRawConverter.convertToTiff).not.toHaveBeenCalled();
		}
	});
});