on: push
name: Sync website FTPS on push
jobs:
    web-deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get latest code
              uses: actions/checkout@v4

            - name: Sync files over FTPS
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ vars.FTP_SERVER }}
                  username: ${{ vars.FTP_USERNAME }}
                  password: ${{ secrets.FTP_PASSWORD }}
                  port: ${{ vars.FTP_PORT }}
                  protocol: ftps
                  local-dir: ${{ vars.GIT_PRODUCTION_DIR }}
                  server-dir: ${{ vars.WEBSITE_URL }}${{ vars.FTP_REMOTE_DIR }}
